### ISSUE TITLE
mongo_head is 34305 blocks behind 

### ISSUE THREAD

**Issue by inertia186** [SteemData/steemdata-api#1]
Going by this: https://api.steemdata.com/health

Is it really more than a day behind?

**Comment by Netherdrake** [comment]
It looks like that is the case.

Currently, there are no functional public steemd nodes, and I am unable to maintain one at this time.

**Comment by inertia186** [comment]
I use this list:

https://ripplerm.github.io/steem-servers/

But I don't know if they have the plug-ins you need.

**Comment by Netherdrake** [comment]
gtg's node is the best
